#version: '3'

services:

  AlarmSystem:
    image: dragonfly_docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alert.yaml:/root/alert.yaml
    command:
      bash -c "python3 /usr/local/src_dragonfly/dragonfly/watchdog.py --config /root/alert.yaml"
